<?php
$sql['allowed_to_access'] = '
SELECT
      MD.ACCESSMODULE AS "Access",
      SUM(USR.USERID) AS "Allowance"
   FROM
      GTFW_MODULE MD
      LEFT JOIN GTFW_GROUP_MODULE GM ON (GM.MODULEID = MD.MODULEID)
      LEFT JOIN GTFW_GROUP G ON (G.GROUPID = GM.GROUPID)
      -- LEFT JOIN GTFW_UNIT U ON (G.UNITID = U.UNITID)
      LEFT JOIN GTFW_USER_GROUP UG ON (UG.GROUPID = GM.GROUPID)
      LEFT JOIN GTFW_USER USR ON (USR.USERID = UG.USERID AND USR.USERID = %s)
   WHERE
      MD.MODULE = %s AND MD.SUBMODULE = %s AND MD.ACTION = %s AND MD.TYPE = %s AND MD.APPLICATIONID = %d
   GROUP BY ACCESSMODULE   
';
   
?>
